# Generated by Django 5.0 on 2024-09-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_interestmodel_intermediate_interestmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resumeModel',
            new_name='BasicInfoModel',
        ),
    ]
