# Generated by Django 3.2.8 on 2024-10-08 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20241001_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('interview_scheduled', 'Interview_scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myApp.jobapplymodel')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
